FROM oven/bun:1-slim


WORKDIR /app

RUN addgroup -S bunapp && adduser -S bunapp -G bunapp


COPY package.json bun.lock ./
RUN bun install --frozen-lockfile


COPY . .


RUN chown -R bunapp:bunapp /app


USER bunapp

EXPOSE 8080

CMD ["bun", "run", "start"]